const data = {
  products: [
    {
      name: 'Product1',
      slug: 'product1-prp',
      category: 'Shirts',
      image: '/images/p1.jpg.webp',
      price: 125,
      countInStock: 10,
      brand: 'nike',
      rating: 4.2,
      numReviews: 10,
      description: 'product1 in stock',
    },
    {
      name: 'Product2',
      slug: 'product2-prp',
      category: 'Shirts',
      image: '/images/p1.jpg.webp',
      price: 125,
      countInStock: 10,
      brand: 'nike',
      rating: 4.2,
      numReviews: 10,
      description: 'product2 in stock',
    },
    {
      name: 'Product3',
      slug: 'product3-prp',
      category: 'Shirts',
      image: '/images/p1.jpg.webp',
      price: 125,
      countInStock: 10,
      brand: 'nike',
      rating: 4.2,
      numReviews: 10,
      description: 'product3 in stock',
    },
    {
      name: 'Product4',
      slug: 'product4-prp',
      category: 'Shirts',
      image: '/images/p1.jpg.webp',
      price: 125,
      countInStock: 10,
      brand: 'nike',
      rating: 4.2,
      numReviews: 10,
      description: 'product4 in stock',
    },
    {
      name: 'Product5',
      slug: 'product5-prp',
      category: 'Shirts',
      image: '/images/p2.jpg.webp',
      price: 125,
      countInStock: 10,
      brand: 'nike',
      rating: 4.2,
      numReviews: 10,
      description: 'product5 in stock',
    },
  ],
};
export default data;
